//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMyCVEntities : DbContext
    {
        public DbMyCVEntities()
            : base("name=DbMyCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Adres> Table_Adres { get; set; }
        public virtual DbSet<Table_Calismalarim> Table_Calismalarim { get; set; }
        public virtual DbSet<Table_Hakkimda> Table_Hakkimda { get; set; }
        public virtual DbSet<Table_Iletisim> Table_Iletisim { get; set; }
        public virtual DbSet<Table_Yetenekler> Table_Yetenekler { get; set; }
        public virtual DbSet<Table_Admin> Table_Admin { get; set; }
    }
}
