//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCv4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Iletisim
    {
        public int Id { get; set; }
        public string Adsoyad { get; set; }
        public string Mail { get; set; }
        public string Mesaj { get; set; }
    }
}
